### ISSUE TITLE
MultiPoolMinerPlugins-v2.6.0.2c-Win

### ISSUE THREAD

**Issue by imrecsoka** [fonyo/MultiPoolMinerPlugins#1]
Hi, i am going to test this and see how it goes.
Am i a little late? or will it be fine?

**Comment by fonyo** [comment]
New multipoolminer version will be coming out soon with a lot of new features and important fixes, I think you should hold off for now. I will update MPMP later.

**Comment by imrecsoka** [comment]
Also getting that stupid bug with DAG 156 instead of DAG 149, it really irritates me.
I just keep retrying until it is fine.
Nicehasminer seems to  be better behaved.
I want to give up on mining, its a real pain.
I have tried to spend and get in to this but really its a real pain.
Developers could not be bothered to fix their wallets so that u can solo mine.
Example, Bitsend and Monacoin they dont have working wallets they have broken the listening service so you can not connect i get ridiculous answers like they are looking into it and i must please use a pool.
anyways, thanks for listening

**Comment by fonyo** [comment]
You shouldn't be solo mining unless you have 100+ GPU farms. Or is that the case?

**Comment by fonyo** [comment]
Also, it is better to stick with well-established coins that do have wallets or why not just use the nicehash miners if you are struggling or simply mine on MPH and mine the top coin and get it auto exchanged. Years ago, we didn't have any of these awesome programs and multipools that increase profits, I would say it is at least a 100 times easier to mine now and get good profit than back then.

Mining is for geeks who enjoy doing things like messing around with code, software, OC, configs. It is definitely not for everyone.

**Comment by fonyo** [comment]
OK, I am closing this.

**Comment by imrecsoka** [comment]
no, i have 3 RX470's i am trying.
I have mined a few Bitsend blocks , but i mean it takes 1-2 days for 1 block.
I am just trying any dam coin. I am just trying what i am sure everybody is 
i just need further help from somebody who cares to help me
